language: java
deploy:
  provider: releases
  api_key:
    secure: z2/4A5ax5qN93cmPvi9wU2/bCCtm+UsHbqeaeqwaCJ/dyozAaj+NYD0zIpFu8pP2dOnWI0INWY/VOZkXCAnAib1bbwtge5xjthaZHbIJmC93tqNwJB9Zd8xv304Xdrk9WqDudbzeKH2+W1zQVcKbf26cmpxVCeLL+w9OsBnO9tsm/ub8oVaxJQQsbpwz3zF3JPUVqQtk26eTGnAdtHk+OOBXNJJoK8CQLI0U7Ov1BDb5rc3OefyYZH56szj/0syFD56wxYJ3Iy9G7kycJ6593iuwUfatjHRHJlKE6FgrfI315+vcRAz51epb3iL0nab/cPdd3YVWTMm6SPHM9xCLV5J7GbZTUayR2PvBf9HAEIsawqeO39tma6OtKYGrfNhZvICjnJ9mrHwsJaqjHRySJ7UtBGdBrVNUrPo3wQ30uc4m0kTsxVvwz8JfOpHCoeSvTIFC85dlV0JS7A8yDnu94ZCLkWzpZtnnH3evEV32K7P4CGYXamem50Ivo2LNvIHmhhct80HmYQwgfICSLYa1hlkZxr/XyB/XwACvsCADhH6D1DTriKzMxLZKUpHT9TZmp8aBW8hcmOzVMHq779SjuwOKmRBMwSppBrYszxkTguyNV/ElHPwAZ+4Qjl2/v7+L23ggJNr7SnRAKRXQ0cQersDz6y/SYra1iEbAKCU9avE=
  file_glob: true
  file: 'build/libs/*'
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-variable-setter-plugin
