language: java
notifications:
  slack:
    secure: IAPqERlETv4T0ZOhVhopLZtuY5+u95KJt33+EtI45nXiZjnvjC/r510FrvVZQ+bM0V5s726mmJ3cNa96zBub7gb336atoHmRMzTWa8IXGb98+6b2hv4mzvdIrcsCBuntgbuJ2UgJXtYzrnSacq2WRcTynJqY0wQhnZzq5QecM4QC8xhaTlNFJAM4SNQfdliT00wZe371ICCRo6C+cC9TA2sXjttbarzL240Qe4ZpGqV5lJcxZR03N4ovs6rhquoGmuU/XxhztIuPbnPjig6kxu3uP7GRmb/DPVcsuvH++W3zM+rOmg4HtQSG4exj70gYl9DPZhVlFxqfG1iN7B9A7RPHU80LKDSPs0Es9HfUZj4ThOV7GyUGP1In0HhE6fw2U973SR23M8sd+n0Ke/3LvyOCTyAmsZt1mDuhj3iOyMA4zChLSOpegD20uAiTC78SwgCbCnDgdXLp9+Fv7kkGzGBHPh1b65DZG4+U859W3c9s2rkNOl0SDJ7XcD+NdaCtWv3Phj8ic+h/2zru+H40NoLykvhmgrjJJCbStjkFUMNr8+rkdRaMGXzr9fYA6TXsn8grJE+Q37w5BzOTLY5rWJyW/4NwQG/mb8d50XUDG4Mb2qknRVQkpsY4TY7w6hSpXA/oa6VVZmaYrQj1FAu8zB3GYCyTn7zImmoiCqwtAOg=
deploy:
  provider: releases
  api_key:
    secure: z2/4A5ax5qN93cmPvi9wU2/bCCtm+UsHbqeaeqwaCJ/dyozAaj+NYD0zIpFu8pP2dOnWI0INWY/VOZkXCAnAib1bbwtge5xjthaZHbIJmC93tqNwJB9Zd8xv304Xdrk9WqDudbzeKH2+W1zQVcKbf26cmpxVCeLL+w9OsBnO9tsm/ub8oVaxJQQsbpwz3zF3JPUVqQtk26eTGnAdtHk+OOBXNJJoK8CQLI0U7Ov1BDb5rc3OefyYZH56szj/0syFD56wxYJ3Iy9G7kycJ6593iuwUfatjHRHJlKE6FgrfI315+vcRAz51epb3iL0nab/cPdd3YVWTMm6SPHM9xCLV5J7GbZTUayR2PvBf9HAEIsawqeO39tma6OtKYGrfNhZvICjnJ9mrHwsJaqjHRySJ7UtBGdBrVNUrPo3wQ30uc4m0kTsxVvwz8JfOpHCoeSvTIFC85dlV0JS7A8yDnu94ZCLkWzpZtnnH3evEV32K7P4CGYXamem50Ivo2LNvIHmhhct80HmYQwgfICSLYa1hlkZxr/XyB/XwACvsCADhH6D1DTriKzMxLZKUpHT9TZmp8aBW8hcmOzVMHq779SjuwOKmRBMwSppBrYszxkTguyNV/ElHPwAZ+4Qjl2/v7+L23ggJNr7SnRAKRXQ0cQersDz6y/SYra1iEbAKCU9avE=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-variable-setter-plugin
